update: ';～～'は使えないらしい。
javaee-memoapp2-1-rk2x4 javaee-memoapp2 Caused by:
java.sql.SQLException: The connection property 'useUnicode' only accepts
values of the form: 'true', 'false', 'yes' or 'no'. The value
'yes;characterEncoding=UTF-8' is not in this set.

Bugzillaの通り、&amp;でつなげてみる